name: Cypress Cucumber Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Use the Node.js version required for your project

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Cucumber Tests
        run: npx cypress run

      - name: Run Newman Tests
        run: newman run postman_collection.json --reporters cli,junit --reporter-junit-export report/newman/newman-report.xml
      
      - name: Cypress Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts  # Choose a name for your artifact
          path: cypress/reports  # Replace with the path to your Cypress test artifacts directory
      
      - name: Upload Newman Test Report
        uses: actions/upload-artifact@v2
        with:
          name: newman-reports
          path: report/newman  # Specify the path to the folder containing your Newman test report files