name: Cypress Tests

on:
  push:
    branches:
      - main  # Replace with the branch where you want to trigger the tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: npm run
        uses: cypress-io/github-action@v4
        with:
          # Specify Browser 
          browser: chrome